version: 2.1

orbs: 
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: cimg/base:2022.06
    resource_class: small
    steps:
      - checkout
      - node/install:
          node-version: '14'
      - node/install-packages
      - run:
          command: npm run test
      - run:
          name: Print SO ulimits
          command: ulimit -a
      - run:
          name: Print xargs limits
          command: xargs --show-limits
workflows:
  test:
    jobs:
      - test
