name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: node:14.17.1
    steps:
      - uses: actions/checkout@v3
      - name: Print SO ulimits
        shell: bash
        run: |
          ulimit -a
      - name: Print xargs limits
        shell: bash
        run: |
          xargs --show-limits
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm test
            
 
